### ISSUE TITLE
Sean Hannity

### ISSUE THREAD

**Issue by robinhood2014** [djacobow/detrumpify#4]
I'm working on adding Sean Hannity to the list of names that Detrumpify blocks, and would like to create a pull request. I can also clean up some messy code.

**Comment by djacobow** [comment]
Yes, the code could use some attention. Was written in haste and then
features accreted and never got a cleanup.

Happy to review your PR!

My main rule for insults is that someone familiar with this particular
blowhard should be able to ID the specific person from the insult. It gets
tricky because so many if these guys have similar wretched qualities.

Best,
David

**Comment by robinhood2014** [comment]
Okay, so, how do I go about submitting my improvements to the code?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by djacobow** [comment]
I haven't done too much group development on github, but I think you
basically create a fork, make your changes, push it back to github and then
make a pull request.

https://opensource.com/article/19/7/create-pull-request-github
